Repository ptycho/ptypy, pull requests merged in 2024-03, with the labels that each got.

#537 Hdf5Loader: allow reading pos from a single entry
  ptypy/experiment/hdf5_loader.py
Labels: 0.8.1

#538 Fix pycuda templates to only load pycuda engines
  templates/accelerate/ptypy_i13_AuStar_farfield_pycuda.py
  templates/accelerate/ptypy_i13_AuStar_nearfield_pycuda.py
  templates/accelerate/ptypy_id22ni_AuStar_focused_pycuda.py
  templates/accelerate/ptypy_laser_logo_focused_pycuda.py
  templates/accelerate/ptypy_minimal_prep_and_run_pycuda.py
  templates/engines/pycuda/moonflower_DM_ML_pycuda.py
  templates/engines/pycuda/moonflower_DM_pycuda.py
  templates/engines/pycuda/moonflower_DM_pycuda_nostream.py
  templates/engines/pycuda/moonflower_EPIE_ML_pycuda.py
  templates/engines/pycuda/moonflower_EPIE_pycuda.py
  templates/engines/pycuda/moonflower_ML_ML_pycuda.py
  templates/engines/pycuda/moonflower_ML_pycuda.py
  templates/engines/pycuda/moonflower_RAAR_ML_pycuda.py
  templates/engines/pycuda/moonflower_RAAR_pycuda.py
  templates/engines/pycuda/moonflower_SDR_pycuda.py
  templates/live_processing/moonflower_DM_delayed_pycuda.py
  templates/notebooks/moonflower_dm_pycuda.ipynb
  templates/notebooks/moonflower_epie_pycuda.ipynb
  templates/notebooks/moonflower_ml_pycuda.ipynb
  templates/notebooks/moonflower_raar_pycuda.ipynb
  templates/position_refinement/moonflower_posref_DM_pycuda.py
  templates/position_refinement/moonflower_posref_EPIE_pycuda.py
  templates/position_refinement/moonflower_posref_ML_pycuda.py
  templates/position_refinement/moonflower_posref_SDR_pycuda.py
Labels: 0.8.1

#539 Update dependencies for cupy/pycuda
  ptypy/accelerate/cuda_cupy/dependencies.yml
  ptypy/accelerate/cuda_pycuda/dependencies.yml
Labels: 0.8.1

#540 Filtered cufft: update dependencies and better error handling
  cufft/dependencies.yml
  cufft/extensions.py
  cufft/setup.py
Labels: 0.8.1

#541 Fixed link to actions badge
  README.rst
Labels: 0.8.1

#527 gather_dict on local error is big bottleneck for large datasets
  ptypy/accelerate/cuda_cupy/engines/projectional_cupy.py
  ptypy/accelerate/cuda_cupy/engines/projectional_cupy_stream.py
  ptypy/accelerate/cuda_cupy/engines/stochastic.py
  ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda.py
  ptypy/accelerate/cuda_pycuda/engines/projectional_pycuda_stream.py
  ptypy/accelerate/cuda_pycuda/engines/stochastic.py
  ptypy/engines/base.py
Labels: 0.8.1

#487 Option to use full polynomial in ML linesearch
  ptypy/engines/ML.py
Labels: 0.8.1

#504 WIP GPU implementation of FFT-based smoothing in ML
  ptypy/accelerate/base/array_utils.py
  ptypy/accelerate/base/engines/ML_serial.py
  ptypy/accelerate/cuda_common/batched_multiply.cu
  ptypy/accelerate/cuda_cupy/array_utils.py
  ptypy/accelerate/cuda_cupy/engines/ML_cupy.py
  ptypy/accelerate/cuda_cupy/kernels.py
  ptypy/accelerate/cuda_pycuda/array_utils.py
  ptypy/accelerate/cuda_pycuda/engines/ML_pycuda.py
  ptypy/accelerate/cuda_pycuda/fft.py
  ptypy/accelerate/cuda_pycuda/kernels.py
  templates/misc/moonflower_ML_cupy_fft_smoothing.py
  templates/misc/moonflower_ML_pycuda_fft_smoothing.py
  test/accelerate_tests/base_tests/array_utils_test.py
  test/accelerate_tests/cuda_cupy_tests/array_utils_test.py
  test/accelerate_tests/cuda_pycuda_tests/array_utils_test.py
  test/accelerate_tests/cuda_pycuda_tests/fft_setstream_test.py
Labels: trieste-meeting-2023, 0.8.1

#545 Update docs for 0.8.1
  README.rst
  doc/html_templates/ptypysphinx/download.html
  doc/index.rst
  doc/rst_templates/getting_started.tmp
  ptypy/version.py
Labels: 0.8.1

#549 Hotfix: DM_cupy is getting stuck if nccl get_unique_id throws error
  ptypy/accelerate/cuda_cupy/multi_gpu.py
Labels: bug
